name: Fake News Detection

on:
  push:
    #branches: [ main ]
    branches:
      - main
#  pull_request:
#    branches: [ main ]
#  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint with flake8
        run: |
          pipenv run flake8 src
          pipenv run flake8 tests
      - name: Lint with pylint
        run: |
          pipenv run pylint src
          pipenv run pylint tests
